version: '3.1'

services:

  rust-app:
    build: .
    ports:
      - "${API_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - .:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  postgres:
    image: postgres:9.6-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "rust_blogpost_auth_async"

